services:
  # HORNET, main tool. Data storage.
  hornet:
    container_name: ${HORNET_HOSTNAME}
    image: iotaledger/hornet
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "15600:15600/tcp"  # Hornet gossip peers
      - "14626:14626/udp"  # Autopeering port
      - "14265:14265/tcp"  # REST HTTP API port
      - "9029:9029/tcp"    # inx access, IOTA Net eXtensions
    cap_drop:
      - ALL
    volumes:
      - ${HORNET_CONF_PATH}:/app/config_private_tangle.json:ro
      - ${HORNET_SNAPSHOT_PATH}:/app/snapshots
      - ${HORNET_DB_PATH}/privatedb:/app/privatedb
    restart: unless-stopped
    command:
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=${HORNET_HOSTNAME}"
      - "--inx.enabled=true"
      - "--inx.bindAddress=${HORNET_HOSTNAME}:9029"
      - "--debug.enabled=true"
    profiles:
      - run


  # INX-DASHBOARD, Hornet extension.
  inx-dashboard:
    container_name: inx-dashboard
    image: iotaledger/inx-dashboard
    depends_on:
      hornet:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8081:8081/tcp"  # Access to web interface
    command:
      - "--inx.address=${HORNET_HOSTNAME}:9029"
      - "--dashboard.bindAddress=inx-dashboard:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
    profiles:
      - run
