services:
  # BOOTSTRAP-NETWORK, allows to generate the initial network status
  bootstrap-network:
    container_name: bootstrap-network
    image: iotaledger/hornet
    environment:
      - "COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
    volumes:
      - ${HORNET_CONF_PATH}:/app/config_private_tangle.json:ro
      - ${HORNET_SNAPSHOT_PATH}:/app/snapshots
      - ${HORNET_DB_PATH}/privatedb:/app/privatedb
      - ${HORNET_DB_PATH}/state:/app/state
    command:
      - "tool"
      - "bootstrap-private-tangle"
      - "--configFile=/app/config_private_tangle.json"
      - "--snapshotPath=/app/snapshots/full_snapshot.bin"
      - "--databasePath=/app/privatedb"
      - "--cooStatePath=/app/state/coordinator.state"
    profiles:
      - bootstrap


  # HORNET, herramienta principal. Valida los milestones.
  hornet:
    container_name: ${HORNET_HOSTNAME}
    image: iotaledger/hornet
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    ports:
      - "15600:15600/tcp"  # Hornet gossip peers
      - "14626:14626/udp"  # Autopeering port
      - "14265:14265/tcp"  # REST HTTP API port
      - "9029:9029/tcp"    # inx access, IOTA Net? eXtensions
    cap_drop:
      - ALL
    volumes:
      - ${HORNET_CONF_PATH}:/app/config_private_tangle.json:ro
      - ${HORNET_SNAPSHOT_PATH}:/app/snapshots
      - ${HORNET_DB_PATH}/privatedb:/app/privatedb
    restart: unless-stopped
    command:
      - "-c"
      - "config_private_tangle.json"
      - "--node.alias=${HORNET_HOSTNAME}"
      - "--inx.enabled=true"
      - "--inx.bindAddress=${HORNET_HOSTNAME}:9029"
      - "--p2p.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      - "--debug.enabled=true"
    profiles:
      - run


  # INX-DASHBOARD, extensión para la herramienta Hornet. Permite ver información sobre Hornet.
  inx-dashboard:
    container_name: inx-dashboard
    image: iotaledger/inx-dashboard
    depends_on:
      hornet:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8081:8081/tcp"  # Access to web interface
    command:
      - "--inx.address=${HORNET_HOSTNAME}:9029"
      - "--dashboard.bindAddress=inx-dashboard:8081"
      - "--dashboard.auth.passwordHash=577eb97f8faf2af47ff957b00827d6bfe9d05b810981e3073dc42553505282c1"
      - "--dashboard.auth.passwordSalt=e5d8d0bd3bb9723236177b4713a11580c55b69a51e7055dd11fa1dad3b8f6d6c"
      - "--dashboard.auth.identityPrivateKey=1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
    profiles:
      - run

   
  # INX-COORDINATOR, extensión para la herramienta Hornet. Permite coordinar los nodos y
  # el crecimiento de la red. Su tarea es crear milestones a un rango constante.
  inx-coordinator:
    container_name: inx-coordinator
    image: iotaledger/inx-coordinator
    depends_on:
      hornet:
        condition: service_healthy
    environment:
      - "COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c"
    volumes:
      - ${HORNET_DB_PATH}/state:/app/state
    restart: unless-stopped
    command:
      - "--inx.address=${HORNET_HOSTNAME}:9029"
      - "--coordinator.stateFilePath=state/coordinator.state"
      - "--coordinator.blockBackups.enabled=false"
    profiles:
      - run
